notifications:
        email:
                recepients:
                        - jonas.drotleff@gmail.com
                on_success: never
                on_failure: always

language: python
python:
        - "3.6"
env:
        global:
                - LAB_CONFIG="config/dev.cfg"
install:
        - pip install -r requirements.txt
script:
        - echo "test"
