notifications:
    email:
        recepients:
            - jonas.drotleff@gmail.com
        on_success: never
        on_failure: never

dist: xenial
language: python

python:
    - "3.6"
    - "3.7"
    - "nightly"

install:
        - pip install -r requirements.txt

script:
        - python -m unittest